version: 2.0.0.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  GH_TOKEN:
    secure: EhiervZBkremCKMnk/LFCC3XTbLfgu6hfWrxBIDWr9Oxf84OO4BKcH6OyH19WrBf
build_script:
  - cmd: powershell ./build.ps1
test: off
on_success:
  - cmd: powershell ./build.ps1 --target="update-debug-plugin"
  - cmd: powershell ./build.ps1 --target="update-pyro-cli"
  - cmd: powershell ./build.ps1 --target="npm-semantic-release"
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL

  # for my test build distribution
deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: 'papyrus-lang test build $(APPVEYOR_REPO_TAG_NAME)-test$(APPVEYOR_BUILD_NUMBER)'
  description: >
      Manually installable .vsix test build of extension $(APPVEYOR_REPO_TAG_NAME)-$(APPVEYOR_BUILD_NUMBER)
      (Automated build via AppVeyor)
  provider: GitHub
  auth_token:
    secure: EhiervZBkremCKMnk/LFCC3XTbLfgu6hfWrxBIDWr9Oxf84OO4BKcH6OyH19WrBf
  artifact: /.*\.vsix/
  draft: false
  prerelease: true
  on:
    branch: test-build                 # release from master branch only
    APPVEYOR_REPO_TAG: false
