name: GitHub CI

on:
 push:
  paths:
  - dependencies/**
  - src/**
  - build.cake
  - build.ps1
  - .github/workflows/**

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Info
      run: echo 'Ref=${{ github.event.ref }} Pusher=${{ github.event.pusher.name }} Pushed_At=${{ github.event.repository.pushed_at }}'
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Update Debug
      if: success()
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: update-debug-plugin
    - name: Update Pyro
      if: success()
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: update-pyro-cli
    - name: Full Build (default)
      if: success()
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: default
    - name: VSCE Package
      if: success()
      run: > 
        cd src\papyrus-lang-vscode ;
        npm install vsce ;
        mkdir artifact ;
        npx vsce package -o artifact\papyrus-lang-test-${{ github.event.repository.pushed_at }}.vsix
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: papyrus-lang-test-${{ github.event.repository.pushed_at }}.vsix
        path: src\papyrus-lang-vscode\artifact
    - name: Notify Success
      if: success()
      run: >
        Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1 ;
        ./send.ps1 success ${{ secrets.DISCORD_WEBHOOK }}
    - name: Notify Failure
      if: failure() || cancelled()
      run: >
        Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1 ;
        ./send.ps1 failure ${{ secrets.DISCORD_WEBHOOK }}
