name: GitHub CI

on:
 push:
  paths:
  - dependencies/**
  - src/**
  - build.cake
  - build.ps1
  - .github/workflows/**

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Update Debug
      if: success()
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: update-debug-plugin
    - name: Update Pyro
      if: success()
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: update-pyro-cli
    - name: Full Build (default)
      if: success()
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: default
    - name: VSCE Package
      if: success()
      run: > 
        cd src\papyrus-lang-vscode ;
        npm install vsce ;
        mkdir artifact ;
        npx vsce package -o artifact\papyrus-lang-test-${{ github.event.created_at }}.vsix
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: vsix-artifact
        path: src\papyrus-lang-vscode\artifact
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: >
          '${{ GITHUB_WORKFLOW }}:The project ${{ github.event.repository.full_name }} has been executed
          for ${{ github.event.ref }}. (Triggered by ${{ gethub.event.pusher.name }})'
