name: 'GitHub CI: RC Build'

on:
  push:
    branches:
      - '**'
    tags:
      - '*-rc*'


jobs:
  build_rc_tag:
    runs-on: windows-latest
    env:
      VSIX_NAME: failed_to_set.vsix
    steps:
 
    - name: Compute Values
      uses: actions/github-script@0.3.0
      id: vals
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          core.setOutput("tag_name", context.ref.split('/')[2]);
          core.setOutput("vsix_name", `papyrus-lang-${ process.env.TAG_NAME }.vsix`);
          if (context.commits) {
            let msgs = [];
            for (let commit of context.commits) {
              msgs.push(` \`${ commit.sha.substr(0,5) }\` ${ commit.author.name } - \`${ commit.message }\``);
            }
            core.setOutput("commit_msgs", msgs.join('\n'));
          }
 
    - name: Notify RC Build Started
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: warn
        description: |
          New **Release Candidate** build [${{ github.workflow }} \(${{ steps.vals.tag_name }}\)](https://github.com/rjstone/papyrus-lang/actions)
          started by ${{ github.actor }}.
          (**${{ github.repository }}** got **${{ github.event_name }}** for **${{ steps.vals.tag_name }}**)
          'Building: ${{ steps.vals.vsix_name }}'
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
 
    - name: Checkout
      uses: actions/checkout@v1
 
    - name: Setup Nuget.exe
      if: success()
      uses: warrenbuckley/Setup-Nuget@v1
 
    - name: Update Debug
      if: success()
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: update-debug-plugin
 
    - name: Update Pyro
      if: success()
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: update-pyro-cli
 
    - name: Full Build (default)
      if: success()
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: default
 
    - name: VSCE Package
      if: success()
      run: > 
        cd src\papyrus-lang-vscode ;
        npm install vsce ;
        mkdir artifact ;
        npx vsce package -o artifact\${{ steps.vals.vsix_name }}
 
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.vals.vsix_name }}
        path: src\papyrus-lang-vscode\artifact\${{ steps.vals.vsix_name }}
 
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release Candidate ${{ steps.vals.tag_name }}
        body: |
          Release Candidate ${{ steps.vals.tag_name }}
        draft: true
        prerelease: true
 
    - name: Upload Release Asset
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: src\papyrus-lang-vscode\artifact\${{ steps.vals.vsix_name }}
        asset_name: ${{ steps.vals.vsix_name }}
        asset_content_type: application/vsix

    # Notifications
    - name: Notify Success
      if: success()
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        description: '**Build Succeeded!** URL: ${{ steps.upload_release_asset.browser_download_url }}'
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

    - name: Notify Failure
      if: failure()
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: error
        description: '**Build Failed!** ${{ steps.vals.vsix_name }}'
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

    - name: Notify Cancelled
      if: cancelled()
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: warn
        description: '**Build Cancelled!** ${{ steps.vals.vsix_name }}'
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
